name: Build and Push Docker Image

on:
  push:
    branches:
      - karsajobs-docker-hub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        run: |
          # Add any additional setup steps here, if needed

          # Build Docker Image
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/karsajobs:latest .

          # Log in to Docker Hub
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

          # Push Docker Image to Docker Hub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/karsajobs:latest

        working-directory: ${{ github.workspace }}
