name: Build and Push Docker Image

# Event trigger: akan dijalankan saat ada push ke branch karsajobs-docker-hub
on:
  push:
    branches:
      - karsajobs-ui-docker-hub

# Job untuk melakukan build dan push Docker image
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Langkah pertama: Checkout kode dari repositori
      - name: Checkout kode
        uses: actions/checkout@v2

      # Langkah kedua: Menjalankan skrip build_push_image_karsajobs-ui.sh
      - name: Build and Push Docker Image
        run: |
          # Mengubah izin skrip menjadi eksekusi
          chmod +x build_push_image_karsajobs_ui.sh
          # Menjalankan skrip build_push_image_karsajobs_ui.sh
          ./build_push_image_karsajobs_ui.sh
        working-directory: ${{ github.workspace }}

      # Langkah ketiga: Login ke Docker Hub menggunakan informasi rahasia
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      # Langkah keempat: Melakukan push Docker image ke Docker Hub
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/karsajobs-ui:latest
        working-directory: ${{ github.workspace }}
