name: Build and Push Docker Image

on:
  push:
    branches:
      - karsajobs-docker-hub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        run: |
          chmod +x build_push_image_karsajobs.sh
          ./build_push_image_karsajobs.sh
        working-directory: ${{ github.workspace }}

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/karsajobs:latest
        working-directory: ${{ github.workspace }}
