# Nama tindakan: Build and Push Docker Image
name: Build and Push Docker Image

# Tindakan ini akan dijalankan ketika ada push ke repositori pada cabang tertentu.
on:
  push:
    branches:
      - karsajobs-ui-docker-hub

# Job yang akan dijalankan pada runner Ubuntu terbaru. Anda dapat mengganti runner sesuai kebutuhan.
jobs:
  # Job bernama 'build'
  build:
    # Menjalankan job pada sistem operasi Ubuntu terbaru.
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dijalankan dalam job ini.
    steps:
      # Langkah pertama: Checkout kode dari repositori.
      - name: Checkout code
        uses: actions/checkout@v2

      # Langkah kedua: Log in to Docker Hub menggunakan informasi rahasia.
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Langkah ketiga: lint Dockerfile menggunakan hadolint.
      - name: lint-dockerfile
        run: |
          # Install hadolint
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint

          # Run hadolint
          hadolint Dockerfile
        working-directory: ${{ github.workspace }}

      # Langkah keempat: Build Docker Image.
      - name: Build Docker Image
        run: |
          # Menjalankan perintah untuk membangun Docker image dengan tag sesuai nama pengguna Docker Hub.
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/karsajobs-ui:latest .
        working-directory: ${{ github.workspace }}

      # Langkah kelima: Push Docker Image ke Docker Hub.
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/karsajobs-ui:latest
        working-directory: ${{ github.workspace }}
