# Nama tindakan: Build and Push Docker Image
name: Build and Push Docker Image

# Tindakan ini akan dijalankan ketika ada push ke repositori pada cabang tertentu.
on:
  push:
    branches:
      - karsajobs-ui  # Ganti dengan nama cabang default repositori Anda

# Job yang akan dijalankan pada runner Ubuntu terbaru. Anda dapat mengganti runner sesuai kebutuhan.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Langkah pertama: Checkout kode dari repositori.
    - name: Checkout code
      uses: actions/checkout@v2

    # Langkah kedua: Log in to GitHub Packages menggunakan GitHub Token.
    - name: Log in to GitHub Packages
      run: echo "${{ secrets.GHCR_GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_GITHUB_USERNAME }} --password-stdin

    # Langkah ketiga: Build Docker Image.
    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/${{ secrets.GHCR_GITHUB_USERNAME }}/${{ secrets.GHCR_GITHUB_REPOSITORY }}/karsajobs-ui:latest .
      working-directory: ${{ github.workspace }}
    
    # Langkah keempat: Push Docker Image ke GitHub Packages.
    - name: Push Docker Image to GitHub Packages
      run: |
        docker push ghcr.io/${{ secrets.GHCR_GITHUB_USERNAME }}/${{ secrets.GHCR_GITHUB_REPOSITORY }}/karsajobs-ui:latest